# Generated by Django 3.2.7 on 2021-09-08 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_column='brand', max_length=255, verbose_name='Brand')),
                ('model', models.CharField(db_column='model', max_length=255, verbose_name='Model')),
                ('body_type', models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Truck', 'Truck'), ('Van', 'Van'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], db_column='body_type', max_length=20, verbose_name='Body type')),
                ('year_of_issue', models.IntegerField(choices=[(2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900)], db_column='year_of_issue', default=2021, verbose_name='Year of issue')),
                ('color', models.CharField(db_column='color', max_length=255, verbose_name='Color')),
                ('engine_volume', models.FloatField()),
                ('power', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electricity', 'Electricity')], db_column='fuel_type', max_length=12, verbose_name='Fuel type')),
                ('transmission_type', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automated Manual', 'Automated Manual'), ('Continuously Variable', 'Continuously Variable')], db_column='transmission_type', max_length=30, verbose_name='Transmission type')),
                ('car_drive_type', models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD'), ('4WD', '4WD')], db_column='car_drive_type', max_length=35, verbose_name='Car drive type')),
                ('license_plate', models.CharField(db_column='license_plate', max_length=10, unique=True, verbose_name='License plate')),
                ('number_of_seats', models.IntegerField()),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
                ('price', models.FloatField()),
                ('car_status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance')], db_column='car_status', default='Available', max_length=12, verbose_name='Car status')),
                ('publishing_date', models.DateTimeField(db_column='publishing_date', default=django.utils.timezone.now, verbose_name='Publishing date')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(db_column='booking_date', default=django.utils.timezone.now, verbose_name='Booking date')),
                ('date_of_issue', models.DateTimeField(db_column='date_of_issue', verbose_name='Date of issue')),
                ('planned_return_date', models.DateTimeField(db_column='planned_return_date', verbose_name='Planned return date')),
                ('total_days', models.IntegerField(blank=True, db_column='total_days', null=True, verbose_name='Total days')),
                ('is_bill_paid', models.BooleanField(db_column='is_bill_paid', default=False, verbose_name='is bill paid')),
                ('return_date', models.DateTimeField(blank=True, db_column='return_date', null=True, verbose_name='Return date')),
                ('total_payment_amount', models.FloatField(blank=True, db_column='total_payment_amount', null=True, verbose_name='Total payment amount')),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], db_column='request_status', default='Pending', max_length=30, verbose_name='Request status')),
                ('car', models.ForeignKey(db_column='car', on_delete=django.db.models.deletion.CASCADE, to='b_car_rental.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'rent car',
                'verbose_name_plural': 'Rent cars',
                'db_table': 'rent_cars',
            },
        ),
    ]
