# Generated by Django 3.2.7 on 2021-09-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_car_rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='client',
            field=models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='rentcar',
            name='request_responded_by',
            field=models.ForeignKey(blank=True, db_column='request_responded_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='Request responded by'),
        ),
        migrations.AddField(
            model_name='car',
            name='published_by',
            field=models.ForeignKey(db_column='published_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Published by'),
        ),
    ]
