# Generated by Django 3.2.7 on 2021-09-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table='about_us',
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
